server:
  port: ${PORT:0}

spring:
  application:
    name: ms-consumidor
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/my-realm-1
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/my-realm-1
        registration:
          keycloak:
            client-id: backend
            client-secret: secret-backend
            scope: openid
            redirect-uri: http://localhost:${server.port}

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  auth:
    converter:
      resource-id: backend
      principal-attribute: preferred_username