server:
  port: 9090

spring:
  application:
    name: ms-gateway
  security:
    oauth2:
      client:
        provider:
          ms-gateway:
            issuer-uri: http://localhost:8080/realms/my-realm-1
        registration:
          api-gateway-service:
            provider: ms-gateway
            client-id: gateway
            client-secret: secret-gateway
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/oauth2/code/keycloak
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: ms-consumidor
          uri: lb://ms-consumidor
          predicates: Path=/consumidor/**
          #filters: StripPrefix=2
        - id: ms-consumido
          uri: lb://ms-consumido
          predicates: Path=/consumido/**
            #filters: StripPrefix=2

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka